version: "3.8"
services:
  neo4j:
    image: neo4j:4.4.3-community
    ports:
      - 7888:7474
      - 7999:7687
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo-db-data:/data
      - neo-data-conf:/conf
      - neo-db-logs:/logs
      - neo-db-plugins:/plugins

volumes:
  neo-db-data:
  neo-db-conf:
  neo-db-logs:
  neo-db-plugins: