version: '3'

networks:
    mysql-phpmyadmin:
        name: mysql-phpmyadmin
        # use the bridge driver
        driver: bridge

volumes:
    db:
      
services:
    mysql:
        image: mysql:8.0
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: database_name
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3307:3306"
        volumes:
            - db:/var/lib/mysql
        networks:
          mysql-phpmyadmin:
            aliases:
              - mysql

    phpmyadmin:
        image: phpmyadmin:5.2.0
        container_name: phpmyadmin
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        ports:
            - 8091:80
        networks:
          mysql-phpmyadmin:
            aliases:
            - phpmyadmin